version: 2
updates:
  # See documentation for possible values
  - package-ecosystem: maven
    # Location of package manifests
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
